export enum PermissionModule {
  USER_MANAGEMENT = 'USER_MANAGEMENT',
  SHOP_MANAGEMENT = 'SHOP_MANAGEMENT',
  PRODUCT_MANAGEMENT = 'PRODUCT_MANAGEMENT',
  ORDER_MANAGEMENT = 'ORDER_MANAGEMENT',
  KYC_MANAGEMENT = 'KYC_MANAGEMENT',
  CATEGORY_MANAGEMENT = 'CATEGORY_MANAGEMENT',
  SYSTEM_SETTINGS = 'SYSTEM_SETTINGS',
  REPORTS_ANALYTICS = 'REPORTS_ANALYTICS'
}

export enum PermissionAction {
  CREATE = 'CREATE', 
  READ = 'READ', 
  UPDATE = 'UPDATE', 
  DELETE = 'DELETE', 
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  EXPORT = 'EXPORT',
  IMPORT = 'IMPORT',
  ASSIGN = 'ASSIGN', // giao
  REVOKE = 'REVOKE' // thu hồi
}
